### ISSUE TITLE
Fix Main Build and PR Build workflows

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-proto-java#5]
Currently the build fails until a new release of the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto) has been made upstream. This is due to a shortcut to make the release as simple as possible.

For instance: [This Main Build workflow-run](https://github.com/open-telemetry/opentelemetry-proto-java/runs/4517534642?check_suite_focus=true) fails as it attempts to download `https://github.com/open-telemetry/opentelemetry-proto/archive/v0.12.0.zip`, which does not exist yet.

**Comment by jack-berg** [comment]
Solved in #12.
